name: Publish Container

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  
  workflow_dispatch:

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.5.0

      - name: Verify that tag existis in origin/main
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        
      - name: Build container
        uses: docker/build-push-action@v3.2.0 
        with:
          build-args: |
            version=${VERSION}
        
