name: Publish Container

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
  
  workflow_dispatch:

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Verify that tag exists in origin/master
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/master

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV

      - name: Log into docker hub
        uses: docker/login-action@v3.0.0
        with:      
          username: ${{ secrets.DOCKER_ACCOUNT }}
          password: ${{ secrets.DOCKER_TOKEN }}   
          
      - name: Build container
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          build-args: |
            version=${VERSION}
          tags: corehelpers/azurebackup:${{ VERSION }}
        
